### ISSUE TITLE
This does not seem to work for me in chrome.

### ISSUE THREAD

**Issue by jasontalyor7** [rantunes1/yt-load-more-items#1]
This doesn't seem to do anything.  I went to a page with enough comments that there is a "show more" box at the bottom, but it was still there.  The plugin animates but doesn't do anything more.  I am using v 1.0.5.

**Comment by rantunes1** [comment]
Hi jasontalyor7,

Thanks for your feedback. and sorry for such a late reply. 
I think the problem you're experiencing has to do with the way YT uses the 'show more' button on the comments page.
 It will first load all sub threads for the comments already displaying and only then it will start loading some more new comments. 
I tried improve on this behaviour in v1.0.6 so if you're still willing to give it another try I'd very much appreciate it.
